#!/bin/bash

echo "Q1 output:"
dlv -silent -pfilter=q1 example-data.dlv example-queries.dlv

echo ""
echo "Q2 output:"
dlv -silent -pfilter=q2 example-data.dlv example-queries.dlv

echo ""
echo "Q3 output:"
dlv -silent -pfilter=q3 example-data.dlv example-queries.dlv

echo ""
echo "Q4 output:"
dlv -silent -pfilter=q4 example-data.dlv example-queries.dlv

echo ""
echo "Q5 output:"
dlv -silent -pfilter=q5 example-data.dlv example-queries.dlv

